import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Piga Home",
  description:
    "How Piga Home collects, uses, and protects your personal data.",
};

const lastUpdated = "27 April 2026";
const effectiveDate = "27 April 2026";

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-gray-800">
      <header className="mb-10 border-b border-gray-200 pb-6">
        <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
        <p className="mt-2 text-sm text-gray-500">
          <strong>Last updated:</strong> {lastUpdated} &nbsp;·&nbsp;{" "}
          <strong>Effective:</strong> {effectiveDate}
        </p>
      </header>

      <article className="prose prose-gray max-w-none space-y-6 text-base leading-relaxed">
        <section>
          <p>
            This Privacy Policy explains how <strong>Assis Tech Ltd</strong>{" "}
            (&quot;<strong>we</strong>&quot;, &quot;<strong>us</strong>&quot;,
            or &quot;<strong>our</strong>&quot;) collects, uses, shares, and
            protects information when you use the <strong>Piga Home</strong>{" "}
            mobile application and related services (collectively, the
            &quot;Service&quot;).
          </p>
          <p>
            Assis Tech Ltd is a company registered in England and Wales. By
            using Piga Home, you agree to the practices described in this
            Policy.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            1. Who we are
          </h2>
          <p>
            <strong>Data Controller:</strong> Assis Tech Ltd<br />
            <strong>Registered Office:</strong> 19 Rigby Street, Manchester,
            WA3 3DN, United Kingdom<br />
            <strong>Contact:</strong>{" "}
            <a
              href="mailto:benkaimugul@gmail.com"
              className="text-blue-600 hover:underline"
            >
              benkaimugul@gmail.com
            </a>
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            2. Information we collect
          </h2>

          <h3 className="mt-4 text-lg font-semibold text-gray-900">
            2.1 Information you provide
          </h3>
          <ul className="ml-6 list-disc">
            <li>
              <strong>Account information:</strong> phone number or email
              address, full name, country of residence
            </li>
            <li>
              <strong>Authentication:</strong> One-time passwords (OTPs) sent to
              your phone or email; Google account information (name, email,
              profile picture) if you choose &quot;Continue with Google&quot;
            </li>
            <li>
              <strong>Profile preferences:</strong> language, currency, biometric
              login preference (this preference is stored on your device only)
            </li>
            <li>
              <strong>Referral codes:</strong> codes you enter or share to earn
              referral bonuses
            </li>
          </ul>

          <h3 className="mt-4 text-lg font-semibold text-gray-900">
            2.2 Information generated by your use of the Service
          </h3>
          <ul className="ml-6 list-disc">
            <li>
              <strong>Call records:</strong> destination numbers, duration of
              calls, cost, and timestamps. We do <strong>not</strong> record or
              store the audio content of your calls.
            </li>
            <li>
              <strong>Wallet & transactions:</strong> balance, top-ups,
              subscription history, plan status
            </li>
            <li>
              <strong>Airtime top-ups:</strong> mobile numbers you send airtime
              to (processed via Reloadly)
            </li>
            <li>
              <strong>Device & technical data:</strong> device model, operating
              system version, app version, language settings, push notification
              token (Firebase Cloud Messaging)
            </li>
          </ul>

          <h3 className="mt-4 text-lg font-semibold text-gray-900">
            2.3 Information from your device (with your permission)
          </h3>
          <ul className="ml-6 list-disc">
            <li>
              <strong>Contacts:</strong> only if you grant permission. Contacts
              are read on your device for the dialer; they are{" "}
              <strong>not uploaded to our servers</strong>.
            </li>
            <li>
              <strong>Microphone:</strong> required for making calls. Audio is
              streamed in real time and is not recorded or stored by us.
            </li>
            <li>
              <strong>Biometric (Face ID / fingerprint):</strong> handled
              entirely by your device&apos;s operating system. We do not receive
              or store your biometric data.
            </li>
            <li>
              <strong>Notifications:</strong> push permission is requested so we
              can deliver call and account notifications.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            3. How we use your information
          </h2>
          <ul className="ml-6 list-disc">
            <li>To create and manage your account</li>
            <li>To authenticate you (OTPs, Google Sign-In, biometric flag)</li>
            <li>To route and bill calls you make through the Service</li>
            <li>To process payments and subscription billing</li>
            <li>To send you transactional notifications (call alerts, receipts, account changes)</li>
            <li>To provide customer support</li>
            <li>To detect and prevent fraud, abuse, or unauthorized use</li>
            <li>To comply with legal obligations</li>
          </ul>
          <p>
            We process your data based on (a) performance of our contract with
            you, (b) your consent (where required, e.g. for marketing
            notifications), and (c) our legitimate interests in operating and
            improving the Service.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            4. Who we share your information with
          </h2>
          <p>
            We share data only with the third parties below, and only to the
            extent necessary to operate the Service. We do not sell your
            personal data.
          </p>
          <ul className="ml-6 list-disc">
            <li>
              <strong>Stripe (Stripe, Inc.)</strong> — payment processing for
              subscriptions and top-ups. Stripe may collect and process your
              payment card details directly. See{" "}
              <a
                href="https://stripe.com/privacy"
                className="text-blue-600 hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Stripe&apos;s Privacy Policy
              </a>
              .
            </li>
            <li>
              <strong>Reloadly</strong> — fulfils airtime top-ups to mobile
              numbers you specify.
            </li>
            <li>
              <strong>Google LLC (Google Sign-In, Firebase Cloud Messaging)</strong>{" "}
              — authentication and push notifications.
            </li>
            <li>
              <strong>Twilio</strong> (or equivalent SMS provider) — delivery of
              one-time-password (OTP) text messages.
            </li>
            <li>
              <strong>Asterisk / our hosting provider</strong> — call routing
              and infrastructure.
            </li>
            <li>
              <strong>Law enforcement / regulators</strong> — only when legally
              required (e.g. valid court order or subpoena under applicable
              law).
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            5. International data transfers
          </h2>
          <p>
            Some of our service providers (e.g. Stripe, Google) may process data
            in the United States or other countries outside the United Kingdom
            and European Economic Area. Where we transfer personal data
            internationally, we rely on appropriate safeguards such as the UK
            International Data Transfer Agreement, EU Standard Contractual
            Clauses, or recognised adequacy decisions.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            6. How long we keep your information
          </h2>
          <ul className="ml-6 list-disc">
            <li>
              <strong>Account information:</strong> retained while your account
              is active and for up to 12 months after closure (for fraud,
              accounting, and tax purposes).
            </li>
            <li>
              <strong>Call records and billing data:</strong> retained for 6
              years (UK statutory requirement for accounting records).
            </li>
            <li>
              <strong>OTP codes:</strong> deleted immediately after use or
              expiry (within 10 minutes).
            </li>
            <li>
              <strong>Marketing communications consent:</strong> retained until
              you withdraw it.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            7. Your rights
          </h2>
          <p>
            Subject to applicable law (including UK GDPR and EU GDPR), you have
            the right to:
          </p>
          <ul className="ml-6 list-disc">
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>
              Request deletion of your account and associated personal data
            </li>
            <li>Receive a copy of your data in a portable format</li>
            <li>Object to or restrict certain processing</li>
            <li>Withdraw consent at any time (where processing is based on consent)</li>
            <li>
              Lodge a complaint with the UK Information Commissioner&apos;s
              Office (
              <a
                href="https://ico.org.uk"
                className="text-blue-600 hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                ico.org.uk
              </a>
              ) or your local data-protection authority
            </li>
          </ul>
          <p>
            To exercise any of these rights, email{" "}
            <a
              href="mailto:benkaimugul@gmail.com"
              className="text-blue-600 hover:underline"
            >
              benkaimugul@gmail.com
            </a>
            . We will respond within 30 days.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            8. Account deletion
          </h2>
          <p>
            You can delete your account at any time:
          </p>
          <ul className="ml-6 list-disc">
            <li>
              <strong>From the app:</strong> Account → Delete Account
            </li>
            <li>
              <strong>By email:</strong> send a deletion request to{" "}
              <a
                href="mailto:benkaimugul@gmail.com"
                className="text-blue-600 hover:underline"
              >
                benkaimugul@gmail.com
              </a>{" "}
              from the email address registered to your account
            </li>
          </ul>
          <p>
            Once you confirm deletion, your account and personal data will be
            removed within 30 days, except where we are legally required to
            retain certain records (e.g. billing records for 6 years for tax
            purposes).
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            9. Security
          </h2>
          <p>
            We use industry-standard security measures to protect your data,
            including HTTPS/TLS encryption in transit, encrypted storage of
            authentication credentials, and access controls on our backend
            systems. No system is 100% secure; if you believe your account has
            been compromised, please contact us immediately.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            10. Children
          </h2>
          <p>
            Piga Home is not intended for children under 18. We do not knowingly
            collect personal data from children under 18. If you believe a child
            has provided us with personal data, contact us and we will delete
            it.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            11. Changes to this Policy
          </h2>
          <p>
            We may update this Privacy Policy from time to time. The
            &quot;Last updated&quot; date at the top of this page indicates when
            it was most recently revised. Material changes will be notified
            through the app or by email.
          </p>
        </section>

        <section>
          <h2 className="mt-8 text-2xl font-semibold text-gray-900">
            12. Contact us
          </h2>
          <p>
            For questions about this Privacy Policy or how we handle your data:
          </p>
          <p>
            <strong>Assis Tech Ltd</strong>
            <br />
            19 Rigby Street, Manchester, WA3 3DN, United Kingdom
            <br />
            Email:{" "}
            <a
              href="mailto:benkaimugul@gmail.com"
              className="text-blue-600 hover:underline"
            >
              benkaimugul@gmail.com
            </a>
          </p>
        </section>
      </article>

      <footer className="mt-16 border-t border-gray-200 pt-6 text-sm text-gray-500">
        <p>
          &copy; {new Date().getFullYear()} Assis Tech Ltd · Piga Home is a
          product of Assis Tech Ltd.
        </p>
      </footer>
    </main>
  );
}
